# Copyright (C) 2015-2026: The University of Edinburgh, United Kingdom
#
# This file is part of the gprMax source code base.
#
# gprMax is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# gprMax is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with gprMax. If not, see <https://www.gnu.org/licenses/>.

"""An equal-resolution HSG must advance explicit PMLs, but has no auxiliary PMLs."""

import h5py
import numpy as np
import pytest

import gprMax
from gprMax.model import Model
from gprMax.pml import PML

ITERATIONS = 200
PHI_NAMES = ("EPhi1", "EPhi2", "HPhi1", "HPhi2")
COMPONENTS = ("Ez", "Hy")


def _scene(embedded, absorbing, formulation):
    scene = gprMax.Scene()
    for obj in (
        gprMax.Domain(p1=(0.064,) * 3),
        gprMax.Discretisation(p1=(0.002,) * 3),
        gprMax.TimeWindow(iterations=ITERATIONS),
        gprMax.PMLThickness(thickness=4),
        gprMax.OMPThreads(1),
        gprMax.PMLFormulation(formulation=formulation),
    ):
        scene.add(obj)
    owner = scene
    if embedded:
        owner = gprMax.SubGridHSG(p1=(0.020,) * 3, p2=(0.044,) * 3, ratio=1, id="fine")
        owner.add(gprMax.PMLFormulation(formulation=formulation))
        scene.add(owner)
    if absorbing:
        owner.add(
            gprMax.PMLSlab(
                p1=(0.024, 0.024, 0.024),
                p2=(0.030, 0.040, 0.040),
                maximum_face="x0",
                id="internal_load",
            )
        )
    else:
        # Match precisely the five PEC faces generated by the absorbing slab.
        # This isolates the PML correction from its enclosure and the HSG interface.
        for lower, upper in (
            ((0.024, 0.024, 0.024), (0.024, 0.040, 0.040)),
            ((0.024, 0.024, 0.024), (0.030, 0.024, 0.040)),
            ((0.024, 0.040, 0.024), (0.030, 0.040, 0.040)),
            ((0.024, 0.024, 0.024), (0.030, 0.040, 0.024)),
            ((0.024, 0.024, 0.040), (0.030, 0.040, 0.040)),
        ):
            owner.add(gprMax.Plate(p1=lower, p2=upper, material_id="pec"))
    owner.add(gprMax.Waveform(wave_type="ricker", amp=1, freq=8e9, id="drive"))
    owner.add(
        gprMax.HertzianDipole(p1=(0.036, 0.032, 0.032), polarisation="z", waveform_id="drive")
    )
    owner.add(gprMax.Rx(p1=(0.034, 0.032, 0.032)))
    return scene


@pytest.fixture
def observed_grids(monkeypatch):
    """Observe real builds and PML calls without replacing any numerical work."""
    grids = []
    build = Model.build

    def capture(model):
        result = build(model)
        grids.append(model.subgrids[0] if model.subgrids else model.G)
        return result

    monkeypatch.setattr(Model, "build", capture)
    for stage in ("electric", "magnetic"):
        original = getattr(PML, "update_" + stage)

        def counted(pml, _stage=stage, _original=original):
            attribute = "test_calls_" + _stage
            setattr(pml, attribute, getattr(pml, attribute, 0) + 1)
            result = _original(pml)
            if pml.ID == "internal_load":
                peaks = getattr(pml, "test_phi_peak_norms", {})
                for name in PHI_NAMES[:2] if _stage == "electric" else PHI_NAMES[2:]:
                    norm = np.linalg.norm(getattr(pml, name).astype(np.float64))
                    peaks[name] = max(peaks.get(name, 0.0), norm)
                pml.test_phi_peak_norms = peaks
            return result

        monkeypatch.setattr(PML, "update_" + stage, counted)
    return grids


def _run(scene, target, embedded, precision, **kwargs):
    gprMax.run(
        scenes=[scene],
        outputfile=target,
        subgrid=embedded,
        autotranslate=embedded,
        cpu_precision=precision,
        hide_progress_bars=True,
        log_level=40,
        **kwargs,
    )


def _histories(path, embedded):
    group = "subgrids/fine/rxs/rx1" if embedded else "rxs/rx1"
    with h5py.File(path) as handle:
        return {component: handle[f"{group}/{component}"][...] for component in COMPONENTS}


def _relative_l2(actual, expected):
    # Compare one component at a time: electric and magnetic fields have different units.
    assert np.all(np.isfinite(actual))
    assert np.all(np.isfinite(expected))
    expected_norm = np.linalg.norm(expected.astype(np.float64))
    assert expected_norm > 0
    return float(np.linalg.norm(actual.astype(np.float64) - expected) / expected_norm)


@pytest.mark.integration
@pytest.mark.parametrize("formulation", ["HORIPML", "MRIPML"])
@pytest.mark.parametrize("precision", ["single", "double"])
def test_equal_resolution_internal_pml_matches_uniform_grid(
    tmp_path, observed_grids, record_property, formulation, precision
):
    histories, grids = {}, {}
    for embedded in (False, True):
        for absorbing in (False, True):
            case = ("hsg" if embedded else "uniform") + ("_pml" if absorbing else "_pec")
            target = tmp_path / case
            _run(_scene(embedded, absorbing, formulation), target, embedded, precision, n=1)
            histories[case] = _histories(target.with_suffix(".h5"), embedded)
            grids[case] = observed_grids[-1]

    # ratio=1 deliberately omits the auxiliary boundary slabs, not explicit slabs.
    for case in ("hsg_pec", "hsg_pml"):
        assert grids[case].equal_resolution
        assert set(grids[case].pmls["thickness"].values()) == {0}
    assert grids["hsg_pec"].pmls["slabs"] == []
    assert [slab.ID for slab in grids["hsg_pml"].pmls["slabs"]] == ["internal_load"]

    tolerance = 2e-5 if precision == "single" else 1e-10
    for component in COMPONENTS:
        for suffix in ("pec", "pml"):
            error = _relative_l2(
                histories[f"hsg_{suffix}"][component], histories[f"uniform_{suffix}"][component]
            )
            record_property(f"{suffix}_{component}_relative_l2", error)
            assert error < tolerance, (suffix, component, error)
        # A nonzero pulse alone is insufficient: both solvers must apply a visible
        # correction relative to the otherwise identical PEC-only model.
        for grid_type in ("uniform", "hsg"):
            effect = _relative_l2(
                histories[f"{grid_type}_pml"][component], histories[f"{grid_type}_pec"][component]
            )
            record_property(f"{grid_type}_{component}_pml_effect_relative_l2", effect)
            assert effect > 1e-3

    slabs = {}
    for case in ("uniform_pml", "hsg_pml"):
        grid = grids[case]
        slab = next(item for item in grid.pmls["slabs"] if item.ID == "internal_load")
        slabs[case] = slab
        assert slab.formulation == formulation
        assert grid.pmls["internal_registry"]["internal_load"]["enclosure_complete"]
        for stage in ("electric", "magnetic"):
            count = getattr(slab, "test_calls_" + stage, 0)
            record_property(f"{case}_{stage}_calls", count)
            assert count == ITERATIONS
        for name in PHI_NAMES:
            assert np.count_nonzero(getattr(slab, name)) > 0, (case, name)
    for name in PHI_NAMES:
        actual = getattr(slabs["hsg_pml"], name)
        expected = getattr(slabs["uniform_pml"], name)
        record_property(f"{name}_relative_l2", _relative_l2(actual, expected))
        # At the final step these accumulators have mostly decayed. Scale their
        # error by the largest history norm observed during the reference pulse,
        # so cancellation at late time does not overconstrain single precision.
        peak_norm = slabs["uniform_pml"].test_phi_peak_norms[name]
        assert peak_norm > 0
        error = float(np.linalg.norm(actual.astype(np.float64) - expected) / peak_norm)
        record_property(f"{name}_peak_normalised_l2", error)
        assert error < tolerance, (name, error)


@pytest.mark.integration
def test_equal_resolution_internal_pml_geometry_fixed_resets_histories(
    tmp_path, observed_grids, monkeypatch
):
    reset_states = []
    reuse_geometry = Model.reuse_geometry

    def observe_reset(model):
        slab = model.subgrids[0].pmls["slabs"][0]
        before = {name: np.count_nonzero(getattr(slab, name)) for name in PHI_NAMES}
        result = reuse_geometry(model)
        after = {name: np.count_nonzero(getattr(slab, name)) for name in PHI_NAMES}
        reset_states.append((before, after))
        return result

    monkeypatch.setattr(Model, "reuse_geometry", observe_reset)
    _run(_scene(True, True, "HORIPML"), tmp_path / "fresh", True, "double", n=1)
    _run(
        _scene(True, True, "HORIPML"), tmp_path / "reused", True, "double", n=2, geometry_fixed=True
    )

    assert len(observed_grids) == 3
    assert observed_grids[0] is not observed_grids[1]
    assert observed_grids[1] is observed_grids[2]
    assert len(reset_states) == 1
    before, after = reset_states[0]
    assert all(value > 0 for value in before.values())
    assert set(after.values()) == {0}

    fresh = _histories(tmp_path / "fresh.h5", True)
    for index in (1, 2):
        reused = _histories(tmp_path / f"reused{index}.h5", True)
        for component in COMPONENTS:
            assert np.linalg.norm(fresh[component]) > 0
            np.testing.assert_array_equal(reused[component], fresh[component])

    fresh_slab = observed_grids[0].pmls["slabs"][0]
    reused_slab = observed_grids[1].pmls["slabs"][0]
    for stage in ("electric", "magnetic"):
        assert getattr(fresh_slab, "test_calls_" + stage) == ITERATIONS
        assert getattr(reused_slab, "test_calls_" + stage) == 2 * ITERATIONS
    for name in PHI_NAMES:
        np.testing.assert_array_equal(getattr(reused_slab, name), getattr(fresh_slab, name))
